name: PR

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    name: Check PR Changes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

